#!/bin/bash

curl -o ~/Downloads/discord.tar.gz -L https://discord.com/api/download?platform=linux&format=tar.gz
tar -xzf ~/Downloads/discord.tar.gz -C ~/Downloads &&
rm -rf /usr/local/apps/Discord &&
mv ~/Downloads/Discord /usr/local/apps/ &&
rm ~/Downloads/discord.tar.gz
