#!/bin/bash

USER="ugo"

curl -o /home/$USER/Downloads/discord.tar.gz -L https://discord.com/api/download?platform=linux&format=tar.gz
tar -xzf /home/$USER/Downloads/discord.tar.gz -C /home/$USER/Downloads &&
rm -rf /usr/local/apps/Discord &&
mv /home/$USER/Downloads/Discord /usr/local/apps/ &&
rm /home/$USER/Downloads/discord.tar.gz
