#!/usr/bin/env bash

output=$(cmus-remote -Q 2>/dev/null) || exit 1

file=$(printf '%s\n' "$output" | sed -n 's/^file //p')
[ -z "$file" ] && exit 1

dir=$(dirname -- "$file")

cmus-remote -C "pause"

st -e vidir "$dir"

cmus-remote -C "play"
