#!/bin/bash

MUSIC_DIR="/media/$NUSER/Music"
PLAYLISTS=("A" "B" "C" "S" "SS")

for playlist in "${PLAYLISTS[@]}"; do
    find . -type f -name "\[${playlist}\]*" -exec mv -n {} "$MUSIC_DIR/$playlist/" \;
done
